# Generated by Django 2.0.5 on 2018-09-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CACTEA', '0002_auto_20180914_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cactea',
            options={'verbose_name': 'cactea', 'verbose_name_plural': 'cacteas'},
        ),
        migrations.RenameField(
            model_name='cactea',
            old_name='id',
            new_name='id_IT',
        ),
    ]
