# Generated by Django 2.0.5 on 2018-09-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CACTEA', '0003_auto_20180914_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cactea',
            options={'ordering': ['id_IT'], 'verbose_name': 'cactea', 'verbose_name_plural': 'cacteas'},
        ),
    ]
